version: '3.8'
services:
  # Service untuk Next.js
  nextjs:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql://root:password@db:3306/mydatabase"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev  # Gunakan dev mode jika ingin live reloading

  # Service untuk MySQL
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  # Service untuk Prisma Studio (opsional, untuk debugging DB)
  prisma:
    image: prismagraphql/prisma:latest
    ports:
      - "5555:5555"
    depends_on:
      - db

volumes:
  db-data:
